# Generated by Django 4.1.3 on 2023-04-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(default='rajat', max_length=150, unique=True)),
                ('orphanageusername', models.CharField(default='O1', max_length=150, unique=True)),
                ('orphanagename', models.TextField()),
                ('money', models.IntegerField()),
                ('grains_no', models.FloatField()),
                ('grains', models.CharField(max_length=150)),
                ('books_no', models.IntegerField()),
                ('books', models.CharField(max_length=150)),
            ],
        ),
    ]
