# Generated by Django 4.1.3 on 2023-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilitydonation',
            name='donorname',
            field=models.CharField(default='rajat', max_length=150),
        ),
        migrations.AlterField(
            model_name='utilitydonation',
            name='orphanageusername',
            field=models.CharField(default='O1', max_length=150),
        ),
    ]
