# Generated by Django 4.1.3 on 2023-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_alter_utilitydonation_donorname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorname', models.CharField(default='rajat', max_length=150)),
                ('orphanageusername', models.CharField(default='O1', max_length=150)),
                ('orphanagename', models.TextField()),
                ('Service', models.CharField(max_length=150)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
