# Generated by Django 4.1.3 on 2023-04-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0004_rename_service_servicedonation_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedonation',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
