# Generated by Django 4.1.3 on 2023-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0006_donorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='username',
            field=models.CharField(default='rajat', max_length=150, unique=True),
        ),
    ]
