# Generated by Django 4.1.3 on 2023-05-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0007_donorprofile_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donorusername', models.CharField(max_length=150)),
                ('orphanageusername', models.CharField(max_length=150)),
                ('orphanagename', models.TextField()),
                ('reason', models.CharField(max_length=150)),
                ('mobile', models.BigIntegerField()),
            ],
        ),
    ]
