# Generated by Django 4.1.3 on 2023-05-03 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0008_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='status',
            field=models.CharField(default='pending', max_length=150),
        ),
    ]
