# Generated by Django 4.1.3 on 2023-04-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage_Display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='dhruv', max_length=150, unique=True)),
                ('name', models.TextField()),
                ('img', models.ImageField(upload_to='pics')),
                ('location', models.TextField()),
                ('weblink', models.TextField()),
            ],
        ),
    ]
