# Generated by Django 4.1.3 on 2023-05-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion', models.TextField()),
            ],
        ),
    ]
