# Generated by Django 4.1.3 on 2023-04-08 21:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orphanage_Details',
            fields=[
                ('o_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('o_name', models.CharField(max_length=100, unique=True)),
                ('o_img', models.ImageField(upload_to='pics')),
                ('o_state', models.CharField(max_length=100)),
                ('o_city', models.CharField(max_length=100)),
                ('o_district', models.CharField(max_length=100)),
                ('o_address', models.TextField()),
                ('weblink', models.TextField()),
            ],
        ),
    ]
