# Generated by Django 4.1.3 on 2023-04-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orphanage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orphanage_details',
            old_name='weblink',
            new_name='o_weblink',
        ),
    ]
