# Generated by Django 4.1.3 on 2023-05-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orphanage', '0004_orphanage_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphanage_events',
            name='e_desc',
            field=models.TextField(default='null'),
        ),
    ]
